/* eslint-disable prettier/prettier */
export const ADD_RESUILT_MEMBER_REQUEST = 'ADD_RESUILT_MEMBER_REQUEST';
export const ADD_RESUILT_MEMBER_SUCCESS = 'ADD_RESUILT_MEMBER_SUCCESS';

export const GET_PROFILE_MEMBER_REQUEST = 'GET_PROFILE_MEMBER_REQUEST';
export const GET_PROFILE_MEMBER_SUCCESS = 'GET_PROFILE_MEMBER_SUCCESS';

export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

export const SEARCH_EMAIL_REQUEST = 'SEARCH_EMAIL_REQUEST';
export const SEARCH_EMAIL_SUCCESS = 'SEARCH_EMAIL_SUCCESS';

export const CHECK_OTP_REQUEST = 'CHECK_OTP_REQUEST';
export const CHECK_OTP_SUCCESS = 'CHECK_OTP_SUCCESS';

export const CHANGE_PASS_REQUEST = 'CHANGE_PASS_REQUEST';
export const CHANGE_PASS_SUCCESS = 'CHANGE_PASS_SUCCESS';

export const ALL_MEMBER_SUCCESS = 'ALL_MEMBER_SUCCESS';

export const ENJECT_MEMBER_SUCCESS = 'ENJECT_MEMBER_SUCCESS';
